export interface ProductData {
  name: string;
  category: "meal" | "snack" | "drink";
  price: number;
  description: string;
  ingredients: string;
  nutritional_info: {
    net_weight: string;
    energy_kcal: number;
    proteins: number;
    carbs: number;
    fats: number;
    fiber: number;
    salt: number;
    per: string;
  };
  origin_info: string;
  certifications: string[];
  allergen_free: string[];
  image_emoji: string;
  image_url: string;
  color_from: string;
  color_to: string;
  is_vegan: boolean;
  is_vegetarian: boolean;
}

export const products: ProductData[] = [
  // === PLATS PRÉPARÉS (8) ===
  {
    name: "Poulet rôti & riz basmati",
    category: "meal",
    price: 12.90,
    description: "Filet de poulet rôti aux herbes de Provence, accompagné de riz basmati parfumé et légumes grillés.",
    ingredients: "Filet de poulet suisse (35%), riz basmati, courgettes, poivrons rouges, huile d'olive, herbes de Provence, sel, poivre.",
    nutritional_info: { net_weight: "350 g", energy_kcal: 155, proteins: 14.5, carbs: 17, fats: 3.5, fiber: 1.2, salt: 0.72, per: "100g" },
    origin_info: "Poulet suisse label de la Broye, riz sélectionné par Transgourmet Suisse SA (Lausanne). Préparé dans un atelier 100% sans allergènes en Suisse romande.",
    certifications: ["Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🍗",
    image_url: "/products/poulet-roti.png",
    color_from: "#D97706",
    color_to: "#92400E",
    is_vegan: false,
    is_vegetarian: false,
  },
  {
    name: "Bowl quinoa & légumes",
    category: "meal",
    price: 11.50,
    description: "Bowl coloré de quinoa tricolore avec légumes de saison rôtis et vinaigrette au citron.",
    ingredients: "Quinoa tricolore (30%), patates douces, brocolis, pois chiches, carottes, huile d'olive, jus de citron, cumin, sel.",
    nutritional_info: { net_weight: "320 g", energy_kcal: 125, proteins: 5.5, carbs: 19, fats: 3.5, fiber: 3.5, salt: 0.52, per: "100g" },
    origin_info: "Quinoa sélectionné par Coopérative Bio Romandie (Moudon, VD), légumes suisses de saison. Atelier 100% sans allergènes.",
    certifications: ["Bio", "Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🥗",
    image_url: "/products/bowl-quinoa.png",
    color_from: "#059669",
    color_to: "#065F46",
    is_vegan: true,
    is_vegetarian: true,
  },
  {
    name: "Saumon grillé & purée",
    category: "meal",
    price: 14.90,
    description: "Pavé de saumon grillé accompagné d'une purée de pommes de terre maison et haricots verts.",
    ingredients: "Saumon d'Écosse (35%), pommes de terre, haricots verts, huile d'olive, aneth, sel, poivre.",
    nutritional_info: { net_weight: "300 g", energy_kcal: 148, proteins: 13.5, carbs: 11.5, fats: 5.5, fiber: 1.5, salt: 0.62, per: "100g" },
    origin_info: "Saumon sélectionné et distribué par Pistor AG (Rotkreuz, ZG), pommes de terre suisses. Atelier 100% sans allergènes.",
    certifications: ["Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🐟",
    image_url: "/products/saumon-grille.png",
    color_from: "#F97316",
    color_to: "#C2410C",
    is_vegan: false,
    is_vegetarian: false,
  },
  {
    name: "Curry thaï au tofu",
    category: "meal",
    price: 10.90,
    description: "Curry vert thaïlandais crémeux au lait de coco avec tofu soyeux et légumes croquants.",
    ingredients: "Tofu (25%), lait de coco, courgettes, poivrons, pâte de curry vert (sans allergènes), riz jasmin, basilic thaï, sel.",
    nutritional_info: { net_weight: "350 g", energy_kcal: 128, proteins: 6.5, carbs: 16, fats: 4.8, fiber: 2.2, salt: 0.78, per: "100g" },
    origin_info: "Tofu artisanal suisse (Lausanne, VD), épices sélectionnées par Transgourmet Suisse SA (Lausanne). Atelier 100% sans allergènes.",
    certifications: ["Bio", "Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🍛",
    image_url: "/products/curry-thai.png",
    color_from: "#16A34A",
    color_to: "#166534",
    is_vegan: true,
    is_vegetarian: true,
  },
  {
    name: "Risotto aux champignons",
    category: "meal",
    price: 11.90,
    description: "Risotto crémeux aux champignons des bois, parfumé au thym et au parmesan végétal.",
    ingredients: "Riz arborio (35%), champignons des bois (shiitake, pleurotes), oignon, bouillon de légumes, huile d'olive, levure nutritionnelle, thym, sel.",
    nutritional_info: { net_weight: "320 g", energy_kcal: 138, proteins: 3.5, carbs: 23.5, fats: 3.5, fiber: 1.2, salt: 0.68, per: "100g" },
    origin_info: "Riz arborio sélectionné par Pistor AG (Rotkreuz, ZG), champignons cultivés dans le Jorat (Vaud). Atelier 100% sans allergènes.",
    certifications: ["Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🍄",
    image_url: "/products/risotto-champignons.png",
    color_from: "#78716C",
    color_to: "#44403C",
    is_vegan: true,
    is_vegetarian: true,
  },
  {
    name: "Bœuf bourguignon",
    category: "meal",
    price: 13.90,
    description: "Bœuf mijoté à la bourguignonne avec carottes, pommes de terre et sauce au vin rouge.",
    ingredients: "Bœuf suisse (35%), pommes de terre, carottes, oignons, vin rouge (sans sulfites), bouillon de bœuf, huile d'olive, thym, laurier, sel, poivre.",
    nutritional_info: { net_weight: "350 g", energy_kcal: 138, proteins: 11.5, carbs: 9.5, fats: 5.5, fiber: 1.8, salt: 0.88, per: "100g" },
    origin_info: "Bœuf suisse de pâturage, légumes de Suisse romande. Atelier 100% sans allergènes.",
    certifications: ["Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sesame", "lupin", "mollusques"],
    image_emoji: "🥩",
    image_url: "/products/boeuf-bourguignon.png",
    color_from: "#991B1B",
    color_to: "#7F1D1D",
    is_vegan: false,
    is_vegetarian: false,
  },
  {
    name: "Wrap poulet-avocat",
    category: "meal",
    price: 9.90,
    description: "Wrap de maïs garni de poulet grillé, avocat frais, tomates et sauce yaourt végétal.",
    ingredients: "Tortilla de maïs, poulet grillé (25%), avocat, tomates, laitue, sauce yaourt de coco, citron vert, coriandre, sel.",
    nutritional_info: { net_weight: "210 g", energy_kcal: 192, proteins: 12, carbs: 18.5, fats: 8, fiber: 2.8, salt: 0.68, per: "100g" },
    origin_info: "Poulet suisse de la Broye, avocats sélectionnés par Pistor AG (Rotkreuz, ZG). Atelier 100% sans allergènes.",
    certifications: ["Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🌯",
    image_url: "/products/wrap-poulet.png",
    color_from: "#A3E635",
    color_to: "#65A30D",
    is_vegan: false,
    is_vegetarian: false,
  },
  {
    name: "Poke bowl saumon",
    category: "meal",
    price: 13.50,
    description: "Poke bowl hawaïen avec saumon mariné, riz vinaigré, edamame, mangue et sauce ponzu.",
    ingredients: "Saumon (30%), riz à sushi, edamame (sans soja allergène), mangue, concombre, avocat, graines de sésame de riz, sauce ponzu sans soja, sel.",
    nutritional_info: { net_weight: "350 g", energy_kcal: 148, proteins: 10.5, carbs: 18.5, fats: 4.5, fiber: 1.8, salt: 0.88, per: "100g" },
    origin_info: "Saumon sélectionné par Pistor AG (Rotkreuz, ZG), riz distribué par Transgourmet Suisse SA (Lausanne). Atelier 100% sans allergènes.",
    certifications: ["Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🍣",
    image_url: "/products/poke-saumon.png",
    color_from: "#FB923C",
    color_to: "#EA580C",
    is_vegan: false,
    is_vegetarian: false,
  },

  // === SNACKS (6) ===
  {
    name: "Energy balls cacao-coco",
    category: "snack",
    price: 4.50,
    description: "Boules énergétiques au cacao cru et noix de coco râpée, naturellement sucrées aux dattes.",
    ingredients: "Dattes Medjool (40%), poudre de cacao cru, noix de coco râpée, huile de coco, poudre de vanille.",
    nutritional_info: { net_weight: "60 g", energy_kcal: 382, proteins: 5, carbs: 55, fats: 15.5, fiber: 7.5, salt: 0.08, per: "100g" },
    origin_info: "Cacao sélectionné par Felchlin AG (Ibach, SZ), noix de coco de qualité supérieure. Confectionné en Suisse.",
    certifications: ["Bio", "Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🍫",
    image_url: "/products/energy-balls.png",
    color_from: "#78350F",
    color_to: "#451A03",
    is_vegan: true,
    is_vegetarian: true,
  },
  {
    name: "Chips de légumes",
    category: "snack",
    price: 3.90,
    description: "Mélange croustillant de chips de betterave, patate douce et panais, légèrement salées.",
    ingredients: "Betteraves (30%), patates douces (30%), panais (30%), huile de tournesol, sel de mer.",
    nutritional_info: { net_weight: "50 g", energy_kcal: 425, proteins: 4, carbs: 53.5, fats: 21.5, fiber: 6.5, salt: 1.25, per: "100g" },
    origin_info: "Légumes racines suisses, huile de tournesol suisse. Production artisanale en Suisse romande.",
    certifications: ["Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🥕",
    image_url: "/products/chips.png",
    color_from: "#E11D48",
    color_to: "#9F1239",
    is_vegan: true,
    is_vegetarian: true,
  },
  {
    name: "Barre protéinée vanille",
    category: "snack",
    price: 3.50,
    description: "Barre riche en protéines végétales à la vanille naturelle de Madagascar.",
    ingredients: "Protéines de pois (25%), sirop de riz, beurre de cacao, poudre de vanille de Madagascar, sel.",
    nutritional_info: { net_weight: "60 g", energy_kcal: 355, proteins: 30, carbs: 37.5, fats: 9.5, fiber: 2.5, salt: 0.42, per: "100g" },
    origin_info: "Protéines végétales distribuées par Pistor AG (Rotkreuz, ZG), arôme vanille naturelle. Fabrication suisse.",
    certifications: ["Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "💪",
    image_url: "/products/barre-vanille.png",
    color_from: "#FDE68A",
    color_to: "#D97706",
    is_vegan: true,
    is_vegetarian: true,
  },
  {
    name: "Crackers sarrasin & romarin",
    category: "snack",
    price: 4.20,
    description: "Crackers artisanaux à la farine de sarrasin et au romarin frais, parfaits pour l'apéro.",
    ingredients: "Farine de sarrasin (60%), huile d'olive, romarin frais, sel de mer, bicarbonate de soude.",
    nutritional_info: { net_weight: "80 g", energy_kcal: 398, proteins: 9.5, carbs: 57.5, fats: 13, fiber: 4.5, salt: 1.45, per: "100g" },
    origin_info: "Sarrasin biologique fourni par Biofarm AG (Kleindietwil, BE), romarin suisse. Cuisson artisanale en Suisse.",
    certifications: ["Sans Gluten", "Bio", "Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🫓",
    image_url: "/products/crakers.png",
    color_from: "#A16207",
    color_to: "#713F12",
    is_vegan: true,
    is_vegetarian: true,
  },
  {
    name: "Fruits secs & graines",
    category: "snack",
    price: 3.90,
    description: "Mélange gourmand de fruits secs et graines de tournesol et courge, source d'énergie naturelle.",
    ingredients: "Raisins secs (25%), graines de tournesol (20%), graines de courge (20%), canneberges séchées (15%), graines de lin (10%), baies de goji (10%).",
    nutritional_info: { net_weight: "50 g", energy_kcal: 428, proteins: 10, carbs: 48, fats: 21.5, fiber: 6.5, salt: 0.08, per: "100g" },
    origin_info: "Graines européennes, fruits secs sélectionnés. Mélangé et conditionné en Suisse.",
    certifications: ["Bio", "Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🥜",
    image_url: "/products/snack-fruits-sec.png",
    color_from: "#B45309",
    color_to: "#78350F",
    is_vegan: true,
    is_vegetarian: true,
  },
  {
    name: "Muffin chocolat sans gluten",
    category: "snack",
    price: 4.90,
    description: "Muffin moelleux au chocolat noir intense, préparé avec de la farine de riz et sans allergènes.",
    ingredients: "Farine de riz (30%), chocolat noir sans lait (20%), compote de pommes, huile de coco, sucre de coco, poudre de cacao, bicarbonate de soude, sel.",
    nutritional_info: { net_weight: "90 g", energy_kcal: 375, proteins: 4.5, carbs: 51, fats: 17.5, fiber: 2.8, salt: 0.45, per: "100g" },
    origin_info: "Chocolat artisanal Felchlin AG (Ibach, SZ), farine de riz sélectionnée par Pistor AG (Rotkreuz, ZG). Pâtisserie suisse.",
    certifications: ["Sans Gluten", "Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🧁",
    image_url: "/products/muffin.png",
    color_from: "#7C2D12",
    color_to: "#431407",
    is_vegan: true,
    is_vegetarian: true,
  },

  // === BOISSONS (6) ===
  {
    name: "Smoothie vert détox",
    category: "drink",
    price: 5.90,
    description: "Smoothie frais aux épinards, pomme verte, concombre et gingembre, riche en vitamines.",
    ingredients: "Épinards frais (25%), pomme verte, concombre, banane, gingembre frais, jus de citron, eau filtrée.",
    nutritional_info: { net_weight: "330 ml", energy_kcal: 52, proteins: 1.2, carbs: 10.5, fats: 0.4, fiber: 1.5, salt: 0.02, per: "100ml" },
    origin_info: "Fruits et légumes suisses de saison. Pressé à froid en Suisse romande.",
    certifications: ["Bio", "Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🥤",
    image_url: "/products/smoothie-vert-detox.png",
    color_from: "#22C55E",
    color_to: "#15803D",
    is_vegan: true,
    is_vegetarian: true,
  },
  {
    name: "Jus d'orange pressé",
    category: "drink",
    price: 4.50,
    description: "Jus d'orange fraîchement pressé, 100% pur fruit sans sucre ajouté.",
    ingredients: "Oranges pressées (100%).",
    nutritional_info: { net_weight: "250 ml", energy_kcal: 43, proteins: 0.7, carbs: 9.5, fats: 0.1, fiber: 0.2, salt: 0.01, per: "100ml" },
    origin_info: "Oranges sélectionnées et distribuées par Transgourmet Suisse SA (Lausanne). Pressé en Suisse.",
    certifications: ["Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🍊",
    image_url: "/products/jus-orange.png",
    color_from: "#F97316",
    color_to: "#EA580C",
    is_vegan: true,
    is_vegetarian: true,
  },
  {
    name: "Lait d'avoine barista",
    category: "drink",
    price: 3.90,
    description: "Lait d'avoine onctueux spécial barista, idéal seul ou dans votre café préféré.",
    ingredients: "Eau, avoine sans gluten (12%), huile de tournesol, sel de mer.",
    nutritional_info: { net_weight: "250 ml", energy_kcal: 48, proteins: 1.0, carbs: 7, fats: 1.5, fiber: 0.5, salt: 0.12, per: "100ml" },
    origin_info: "Avoine certifiée sans gluten fournie par Biofarm AG (Kleindietwil, BE). Produit en Suisse.",
    certifications: ["Sans Gluten", "Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🥛",
    image_url: "/products/lait-avoine.png",
    color_from: "#E5E7EB",
    color_to: "#9CA3AF",
    is_vegan: true,
    is_vegetarian: true,
  },
  {
    name: "Kombucha gingembre-citron",
    category: "drink",
    price: 4.90,
    description: "Kombucha artisanal fermenté au gingembre frais et citron, pétillant et rafraîchissant.",
    ingredients: "Eau filtrée, thé vert biologique, sucre de canne (fermenté), gingembre frais, jus de citron, culture de kombucha.",
    nutritional_info: { net_weight: "330 ml", energy_kcal: 18, proteins: 0, carbs: 3.8, fats: 0, fiber: 0, salt: 0.01, per: "100ml" },
    origin_info: "Thé biologique sélectionné par Transgourmet Suisse SA (Lausanne), gingembre frais suisse. Fermenté artisanalement en Suisse romande.",
    certifications: ["Bio", "Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🍵",
    image_url: "/products/kombucha.png",
    color_from: "#FBBF24",
    color_to: "#D97706",
    is_vegan: true,
    is_vegetarian: true,
  },
  {
    name: "Eau minérale Henniez",
    category: "drink",
    price: 2.50,
    description: "Eau minérale naturelle Henniez, source suisse depuis 1905.",
    ingredients: "Eau minérale naturelle.",
    nutritional_info: { net_weight: "500 ml", energy_kcal: 0, proteins: 0, carbs: 0, fats: 0, fiber: 0, salt: 0.005, per: "100ml" },
    origin_info: "Source de Henniez, canton de Vaud, Suisse.",
    certifications: ["Swiss Made"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "💧",
    image_url: "/products/henniez.png",
    color_from: "#38BDF8",
    color_to: "#0284C7",
    is_vegan: true,
    is_vegetarian: true,
  },
  {
    name: "Thé glacé pêche",
    category: "drink",
    price: 4.50,
    description: "Thé glacé maison à la pêche, légèrement sucré au sirop d'agave.",
    ingredients: "Eau filtrée, thé noir biologique, purée de pêche (15%), sirop d'agave, jus de citron.",
    nutritional_info: { net_weight: "330 ml", energy_kcal: 26, proteins: 0, carbs: 6, fats: 0, fiber: 0, salt: 0.01, per: "100ml" },
    origin_info: "Thé biologique sélectionné par Transgourmet Suisse SA (Lausanne), pêches du Valais suisse. Préparé en Suisse.",
    certifications: ["Bio", "Swiss Made", "Allergen-Free Facility"],
    allergen_free: ["gluten", "crustaces", "oeufs", "poisson", "arachides", "soja", "lait", "fruits-a-coque", "celeri", "moutarde", "sesame", "sulfites", "lupin", "mollusques"],
    image_emoji: "🍑",
    image_url: "/products/the-glace.png",
    color_from: "#FDBA74",
    color_to: "#F97316",
    is_vegan: true,
    is_vegetarian: true,
  },
];
